### ISSUE TITLE
Mac OSX: deepstream install storage postgres, Release for your platform not found

### ISSUE THREAD

**Issue by andystevensname** [deepstreamIO/deepstream.io-storage-postgres#1]
Just a note for anyone else looking for this connector. Download the linux version from the [release page](https://github.com/deepstreamIO/deepstream.io-storage-postgres/releases), remove -linux from the folder name and place `deepstream.io-storage-postgres` into `/deepstream.io-.../lib` and you should be fine.

**Comment by yasserf** [comment]
I can't seem to get postgres builds running vs osx, having issues with roles 

https://travis-ci.org/deepstreamIO/deepstream.io-storage-postgres/jobs/200885969

Once postgres is setup properly this should work fine, but I can't seem to figure it out =(

**Comment by WolframHempel** [comment]
Same problem for @honorcode

**Comment by yasserf** [comment]
That's because Postgres doesn't come setup on a mac on CI

Will look into it asap

**Comment by honorcode** [comment]
Easy enough to just grab the repo source and copy it to the lib dir and run npm install

**Comment by ksteigerwald** [comment]
@honorcode thanks seemed to work... 

if brew cask install => /usr/local/lib/deepstream

**Comment by gerhardcit** [comment]
@yasserf 
In the tutorial video this works on a mac
https://www.youtube.com/watch?v=HJGcWJRbE70&t=18s
but this error now pops up again:
```
deepstream install storage postgres
Error: Not found, see available connectors on https://deepstreamhub.com/open-source/
```
I have postgres running and using it.
Any ideas?

**Comment by gerhardcit** [comment]
What works is to download the previous version zipped file, V1.1.3 in this case

.../v1.1.3/deepstream.io-storage-postgres-mac.zip

unzip it, rename the folder to deepstream.io-storage-postgres 
move it to the deepstream lib folder.

So in the deepstream folder you will this
```
ls -l lib
total 0
drwxr-xr-x@ 10 user  group  340 Oct 24 10:28 deepstream.io-logger-winston
drwx------@ 15 user  group  510 Nov  2 21:33 deepstream.io-storage-postgres
```

**Comment by yasserf** [comment]
deepstream v5 onwards bundles this for us
