### ISSUE TITLE
Broken storage installation

### ISSUE THREAD

**Issue by VojtechBartos** [deepstreamIO/deepstream.io-storage-postgres#14]
Hi there,

looks like latest version 1.1.1 doesn't have zip/tar for each platform built in the release so command `deepstream install storage postgres` is failing with `Release for your platform not found`.

Workaround is just to install previous version `deepstream install storage postgres --version 1.0.1`

**Comment by yasserf** [comment]
Thanks for letting us know. We just released 1.1.3, are you currently using a mac or linux machine?

**Comment by VojtechBartos** [comment]
@yasserf using mac machine, but installing it inside docker image, so linux

**Comment by yasserf** [comment]
latest version should have the linux package uploaded, let us know if that doesn't work

**Comment by VojtechBartos** [comment]
@yasserf works as expected, thanks
