### ISSUE TITLE
Cannot read property 'splice of null

### ISSUE THREAD

**Issue by VRspace4** [deepstreamIO/deepstream.io-storage-postgres#17]
I'm using the latest 3.1.0 version and followed instructions found here:
https://deepstreamhub.com/open-source/integrations/db-postgres/

Windows 7
PostgreSQL v10.0
Node v6.11.4
npm v3.10.10

I'm getting the following error when running deepstream.

> =====================   starting   =====================
> INFO | logger ready: std out/err
> INFO | deepstream version: 3.1.0
> INFO | configuration file loaded from conf\config.yml
> INFO | library directory set to: c:\JP\active-software\deepstream-3.1.0\lib
> INFO | cache ready: local cache
> INFO | authenticationHandler ready: none
> INFO | permissionHandler ready: valve permissions loaded from c:\JP\active-softw
> missions.yml
> c:\JP\active-software\deepstream-3.1.0\lib\deepstream.io-storage-postgres\src\ut
>     .splice( 1 )
>     ^
> 
> TypeError: Cannot read property 'splice' of null
>     at Object.exports.checkVersion (c:\JP\active-software\deepstream-3.1.0\lib\d
> \src\utils.js:51:5)
>     at query (c:\JP\active-software\deepstream-3.1.0\lib\deepstream.io-storage-p
> 13)
>     at Result.client.query (c:\JP\active-software\deepstream-3.1.0\lib\deepstrea
> nector.js:270:9)
>     at Result.Query.handleReadyForQuery (c:\JP\active-software\deepstream-3.1.0\
> tgres\node_modules\pg\lib\query.js:144:10)
>     at Connection.<anonymous> (c:\JP\active-software\deepstream-3.1.0\lib\deepst
> _modules\pg\lib\client.js:180:19)
>     at emitOne (events.js:101:20)
>     at Connection.emit (events.js:188:7)
>     at Socket.<anonymous> (c:\JP\active-software\deepstream-3.1.0\lib\deepstream
> ules\pg\lib\connection.js:133:12)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)

**Comment by VRspace4** [comment]
I found the fix in case someone else needs it:

Open up the file `utils.js` from `deepstream-3.1.0/lib/deepstream.io-storage-postgres/src/` and replace line 50

from:
`.match(/PostgreSQL (\d*)\.(\d*).(\d*)/)`

to:
`.match(/PostgreSQL (\d*)\.(\d*)/)`

**Comment by AlexBHarley** [comment]
I believe this will be fixed by #16 when merged in.
