### ISSUE TITLE
Issue when the postgres username differs from the role name

### ISSUE THREAD

**Issue by jonerer** [deepstreamIO/deepstream.io-storage-postgres#18]
Hello!

We are running a hosted postgres on azure. There, our login name is "deepstream@something", but the role we should be using is "deepstream". That means that when we do something in DS that causes us to create a table we get this problem:

```
routine: 'get_role_oid' } 'error during query \n    CREATE TABLE "ds"."msbeedhqejaaeeff"\n    (\n        id text NOT NULL,\n        val text NOT NULL,\n        PRIMARY KEY (id)\n    )\n    WITH (\n        OIDS = FALSE\n    )\n    TABLESPACE pg_default;\n\n    ALTER TABLE "ds"."msbeedhqejaaeeff"\n    OWNER to "deepstream@something";\n        CREATE TRIGGER "broadcast_update_ds_msbeedhqejaaeeff"\n        AFTER INSERT OR DELETE ON "ds"."msbeedhqejaaeeff"\n        FOR EACH ROW EXECUTE PROCEDURE broadcast_update();NOTIFY "ds", \'CREATE_TABLE:msbeedhqejaaeeff\';'
RECORD_CREATE_ERROR | storage:error: role "deepstream@something" does not exist
```

Caused by statements.js line 66

A simple solution would be to in the writer.js file shave off everything after '@', but I'm unsure if that breaks someone's usecase. So I made a PR that adds a "role" option to the deepstream settings. See PR https://github.com/deepstreamIO/deepstream.io-storage-postgres/pull/19

The new "role" option is optional, and will fall back to username, which should be good for most users

**Comment by yasserf** [comment]
Thanks, closing! (a few years later!) 😅
