### ISSUE TITLE
Add initialization timeout

### ISSUE THREAD

**Issue by PhillippOhlandt** [deepstreamIO/deepstream.io-storage-postgres#2]
Hey,

as discussed with @yasserf, it makes sense to add a `timeout` option to this connector. On connector initialization, the connector would try to connect to the DB until the timeout is over, before throwing an error.

The reason behind it is, that when using DS with postgres via docker (docker-compose), the postgres instance inside the container needs a few seconds to actually boot up. Right now, DS will shut down immediately because the connector can't connect to the DB (because it is still booting).

**Comment by PhillippOhlandt** [comment]
The default timeout value should probably be something near 30 seconds because postgres needs a very long time when you start it the first time.

**Comment by yasserf** [comment]
I thought what we discussed was that it will keep trying to reconnect until it is told to close by deepstream. Having to configure an initial timeout for each plugin won't scale very well and it's very repetitive.

**Comment by PhillippOhlandt** [comment]
Yes, you are right. Trying to reconnect until the `dependencyInitialisationTimeout` setting from DS will stop it is probably the better way.
