### ISSUE TITLE
Plugin installer on macOS is broken

### ISSUE THREAD

**Issue by neonsamurai** [deepstreamIO/deepstream.io-storage-postgres#20]
I have this problem on macOS High Sierra.

The installer puts the node module for the storage connector into a sub-sub directory `/usr/local/lib/deepstream/deepstream.io-storage-postgres/deepstream.io-storage-postgres-mac`. This results in the error 'Could not find node module...' when starting Deepstream.

I could work around the problem in development by moving all files one directory up, but this is a pain for deployment.

Furthermore, right after installing, the installer complains 'No default configuration found'

Edit:

Furthermore I noticed, that the official Docker image also has a broken Postgres storage connector. I don't know if the problems are the same, since they're on different operating systems, but it seems likely, that something in the build process or installer isn't quite right.

Edit 2:

The container on docker hub seems to be alright now. Or I got some things confused.

**Comment by remaininlight** [comment]
As a temporary fix, copying the contents of deepstream.io-storage-postgres-mac up a level into deepstream.io-storage-postgres seems to work.

**Comment by yasserf** [comment]
Seems like the problem is more around the zip within deepstream and not this plugin. Calling unzip via command line works as expected but using another tool ends up with the folder.

**Comment by yasserf** [comment]
This is no longer supported for V5 onwards since postgres is already bundled in db binary.
