### ISSUE TITLE
Possible race condition on buffer flushing?

### ISSUE THREAD

**Issue by sdressler** [deepstreamIO/deepstream.io-storage-postgres#3]
I'm not fully sure whether all my assumptions are correct, so please bear with me. In `connector.js` you are buffering writes to the database by calling `this._writeOperations[ tableName ].add( params.key, value, callback )`. All these are collected and flushed at a regular interval.

To me it seems that while flushing the write there is no protection against adding additional values to the buffer which may lead to not writing values but calling all callbacks since

    for( var i = 0; i < this._callbacks.length; i++ ) {
      this._callbacks[ i ]( error )
    }

goes over all callbacks no matter how many values where actually written.

**Comment by yasserf** [comment]
The idea is the last write wins, and all the callbacks return true if that write happens. It's because the cache is the source of latest truth, so the db doesn't get all the updates.
