### ISSUE TITLE
Is it possible to config "exclude" table creation?

### ISSUE THREAD

**Issue by geohuz** [deepstreamIO/deepstream.io-storage-postgres#46]
I'm wondering if there is a way to exclude some tables from connector so they are not auto created/maintained in connector?

**Comment by jaime-ez** [comment]
Hi, sorry for the late reply

Deepstream only watches the given schema in options, all other tables on different schemas will not be watched by deepstream.

Is this what you mean?

**Comment by geohuz** [comment]
No, actually I want some deepstream records will not have table created in the postgresql schema. We don't have option to exlcude certain table in the configuration file.

**Comment by jaime-ez** [comment]
So you want some records not to be saved in database and keep them in memory only ?
If that's the case you can use the server configuration option `storageExclusionPrefixes` see here: https://deepstream.io/docs/server/configuration/#storageexclusionprefixes

**Comment by geohuz** [comment]
@jaime-ez thanks!
