### ISSUE TITLE
Not usable

### ISSUE THREAD

**Issue by Pedroxam** [deepstreamIO/deepstream.io-storage-postgres#48]
**First Error (from nodejs):**

PostgresConnector is not a constructor :

```
const PostgresConnector = require( '@deepstream/storage-postgres' );
const settings = {
  user: 'postgres',
  database: 'test',
  password: '',
  host: 'localhost',
  port: 5432
}

const connector = new PostgresConnector( settings )
```

Second Error (for adding plugin) :

```
CONFIG_TRANSFORM | Loaded content from C:\Users\Jill\Desktop\deepstream\conf\permissions.yml for fileLoad(permissions.yml)
CONFIG_ERROR | Error loading module, exiting
```

**Comment by jaime-ez** [comment]
HI, sorry the docs weren't updated. you should instantiate as: 
```
const { Connector } = require( '@deepstream/storage-postgres' );
const settings = {
  user: process.env.PG_USER,
  database: process.env.PG_DB,
  password: process.env.PG_PASSWORD,
  host: process.env.PG_HOST,
  port: parseInt( process.env.PG_PORT, 10 )
}

const connector = new Connector( settings )

// start connector
connector.init()
```

Can you share more details about the second error or share your config files ?

**Comment by Pedroxam** [comment]
Hi, thanks for replay, check this image:

![image](https://user-images.githubusercontent.com/6213778/135810312-a6706ae6-5455-4c43-ad51-76640f282b6c.png)

**Comment by jaime-ez** [comment]
your error seems to be related to the permissions section in config...did you made any changes to it?

**Comment by Pedroxam** [comment]
No, I have not make any changes in permissions file or other files,
just i add that code to config.yml

**Comment by jaime-ez** [comment]
Hi, sorry again docs issue.
I use this module via the node api, therefore I never realised before there was a documentation error for the config files. I've updated the readme. In summary, drop the `plugins` keyword and it should work.
